//
//  ReelData.swift
//  VerticalSlots
//
//  Created by Tushar Das on 10/03/2017.
//  Copyright © 2017 Lamig Software. All rights reserved.
//

import Foundation

array rail1 = {“Cat", "Cat", "Cow", "Cat", "Panda", "Cat", "Panda", "Dog", "Cat", "Dog", "Dog", "Panda", "Cat", "Panda", "Dog", "Dog", "Cow", "Dog", "Cow", "Cow", "Cow", "Cat", "Cow", "Cat", "Cow", "Cow", "Cat", "Cow", "Cat", "Dog", "Panda", "Cow", "Cow", "Cat", "Cow", "Cow", "Panda", "Cow", "Cat", "Cat", "Dog", "Dog", "Dog", "Cat", "Cat", "Panda", "Cat", "Dog", "Panda", "Cat", "Cow", "Panda", "Cow", "Cat", "Cat", "Dog", "Dog", "Cow", "Cow", "Dog", "Cat", "Panda", "Cat", "Panda", "Cat", "Cat", "Panda", "Dog", "Dog", "Panda", "Cow", "Dog", "Cat", "Cat", "Dog", "Panda", "Dog", "Cat", "Cat", "Cow", "Cat", "Cat", "Panda", "Panda", "Cow", "Dog", "Cat", "Dog", "Cow", "Dog", "Panda", "Panda", "Cow", "Cow", "Dog", "Panda", "Cow", "Panda", "Cat", "Cow", "Dog", "Panda", "Panda", "Cat", "Dog", "Cow", "Cow", "Dog", "Dog", "Cow", "Cat", "Panda", "Cow", "Cat", "Cat", "Cow", "Cow", "Cow", "Cow", "Cat", "Cat", "Panda", "Panda", "Cow", "Cat", "Panda", "Cat", "Cat", "Panda", "Panda", "Dog", "Cow", "Panda", "Cat", "Cat", "Panda", "Cat", "Dog", "Cat", "Panda", "Dog", "Dog", "Cow", "Dog", "Cow", "Dog", "Dog", "Panda", "Panda", "Panda", "Cow", "Cow", "Cow", "Panda", "Cow", "Cat", "Panda", "Panda", "Cow", "Dog", "Dog", "Panda", "Panda", "Cat", "Dog", "Dog", "Cow", "Panda", "Dog", "Panda", "Panda", "Cat", "Cat", "Panda", "Dog", "Dog", "Cow", "Cow", "Dog", "Dog", "Dog", "Dog", "Dog", "Cow", "Dog", "Panda", "Dog", "Dog", "Cow", "Cat", "Dog", "Cow", "Dog", "Dog", "Panda", "Cow", "Cow", "Dog", "Panda", “Dog""d


    array rail2 = {"Dog", "Cat", "Panda", "Panda", "Cat", "Panda", "Panda", "Cow", "Dog", "Panda", "Panda", "Cat", "Cat", "Cow", "Dog", "Cat", "Cat", "Cat", "Cat", "Cat", "Panda", "Cat", "Dog", "Panda", "Dog", "Cow", "Panda", "Panda", "Cow", "Cow", "Cat", "Dog", "Dog", "Cow", "Cow", "Dog", "Cat", "Cow", "Dog", "Cow", "Dog", "Dog", "Dog", "Dog", "Cow", "Panda", "Panda", "Cat", "Dog", "Panda", "Dog", "Dog", "Cow", "Cat", "Panda", "Dog", "Panda", "Cow", "Panda", "Cat", "Panda", "Cat", "Panda", "Panda", "Cat", "Cow", "Panda", "Cat", "Cat", "Cow", "Panda", "Cow", "Cow", "Panda", "Panda", "Dog", "Dog", "Dog", "Dog", "Panda", "Cat", "Cow", "Dog", "Panda", "Panda", "Cat", "Panda", "Cat", "Panda", "Cat", "Cat", "Cat", "Panda", "Cow", "Cow", "Cow", "Dog", "Dog", "Panda", "Cat", "Cat", "Panda", "Dog", "Cow", "Cat", "Cow", "Cat", "Panda", "Panda", "Dog", "Dog", "Cat", "Cow", "Panda", "Cat", "Cat", "Cow", "Panda", "Panda", "Panda", "Panda", "Cat", "Cat", "Cow", "Panda", "Dog", "Cow", "Cat", "Dog", "Cow", "Dog", "Dog", "Cat", "Dog", "Dog", "Panda", "Panda", "Cat", "Cat", "Panda", "Dog", "Panda", "Cat", "Cow", "Panda", "Dog", "Cat", "Dog", "Cat", "Cat", "Cow", "Cow", "Cow", "Cat", "Dog", "Panda", "Cow", "Cat", "Panda", "Dog", "Cat", "Cat", "Panda", "Dog", "Panda", "Panda", "Panda", "Panda", "Cow", "Cat", "Cow", "Panda", "Dog", "Panda", "Panda", "Panda", "Panda", "Cow", "Dog", "Cat", "Panda", "Dog", "Cat", "Panda", "Panda", "Dog", "Dog", "Panda", "Panda", "Dog", "Panda", "Panda", "Cat", "Panda", "Dog", "Panda", "Cat", "Panda", "Cow", "Dog"}

    array rail 3 = {"Panda", "Cow", "Panda", "Cat", "Cat", "Dog", "Panda", "Panda", "Panda", "Panda", "Cow", "Cat", "Cat", "Cow", "Cow", "Panda", "Panda", "Panda", "Panda", "Panda", "Dog", "Cat", "Panda", "Dog", "Dog", "Panda", "Panda", "Dog", "Cow", "Panda", "Dog", "Panda", "Cat", "Cow", "Dog", "Cat", "Cat", "Cat", "Cow", "Dog", "Cat", "Dog", "Cow", "Cow", "Cow", "Dog", "Dog", "Cat", "Dog", "Panda", "Panda", "Cow", "Panda", "Panda", "Cow", "Dog", "Panda", "Dog", "Cat", "Panda", "Cow", "Cow", "Cow", "Cow", "Cat", "Cat", "Cow", "Cat", "Panda", "Panda", "Panda", "Cat", "Dog", "Cow", "Cat", "Cow", "Dog", "Dog", "Panda", "Dog", "Cat", "Dog", "Cat", "Cow", "Panda", "Cow", "Panda", "Cat", "Cat", "Dog", "Cow", "Dog", "Dog", "Dog", "Panda", "Cow", "Panda", "Panda", "Panda", "Cat", "Cow", "Cow", "Dog", "Cat", "Dog", "Dog", "Cow", "Panda", "Cow", "Cat", "Panda", "Cow", "Cow", "Panda", "Panda", "Dog", "Cat", "Panda", "Dog", "Cow", "Dog", "Dog", "Panda", "Panda", "Cow", "Cat", "Cow", "Cow", "Cow", "Dog", "Cat", "Cat", "Cat", "Cow", "Dog", "Cow", "Dog", "Dog", "Cat", "Dog", "Cow", "Cow", "Dog", "Cow", "Dog", "Panda", "Dog", "Cow", "Panda", "Panda", "Cow", "Cat", "Cat", "Dog", "Cat", "Dog", "Cat", "Dog", "Cow", "Cow", "Dog", "Cow", "Panda", "Cat", "Cow", "Cow", "Cow", "Cat", "Cow", "Cat", "Cow", "Dog", "Cat", "Cat", "Cow", "Cow", "Dog", "Panda", "Panda", "Cat", "Panda", "Cow", "Dog", "Cat", "Cat", "Dog", "Dog", "Panda", "Panda", "Cow", "Panda", "Cat", "Cat", "Panda", "Panda", "Cow", "Dog", "Panda", "Panda", "Panda"}

    array rail 4 ={"Cow", "Cow", "Cow", "Panda", "Dog", "Panda", "Cow", "Cow", "Cat", "Cow", "Cow", "Dog", "Dog", "Panda", "Panda", "Panda", "Cow", "Cow", "Cat", "Dog", "Dog", "Cat", "Cat", "Dog", "Cat", "Cat", "Dog", "Cat", "Cow", "Dog", "Cow", "Cow", "Cow", "Dog", "Cat", "Cat", "Panda", "Cow", "Dog", "Cat", "Cat", "Cow", "Cow", "Cat", "Panda", "Cat", "Cat", "Dog", "Dog", "Dog", "Dog", "Cow", "Cow", "Cat", "Cow", "Dog", "Cat", "Dog", "Cow", "Cat", "Panda", "Cow", "Cow", "Dog", "Dog", "Dog", "Panda", "Panda", "Dog", "Cat", "Dog", "Cow", "Panda", "Cow", "Panda", "Cat", "Dog", "Panda", "Dog", "Cat", "Cow", "Panda", "Cat", "Dog", "Panda", "Cat", "Cow", "Dog", "Cow", "Cat", "Cat", "Panda", "Cat", "Dog", "Panda", "Cow", "Cat", "Cat", "Cow", "Dog", "Dog", "Cow", "Panda", "Cow", "Cat", "Cow", "Panda", "Cat", "Panda", "Dog", "Cow", "Dog", "Cow", "Cow", "Dog", "Cat", "Cat", "Dog", "Cat", "Panda", "Cow", "Panda", "Cat", "Cow", "Panda", "Dog", "Panda", "Dog", "Cat", "Panda", "Dog", "Panda", "Dog", "Dog", "Cat", "Panda", "Dog", "Cow", "Cat", "Cow", "Cat", "Dog", "Dog", "Cow", "Cow", "Panda", "Panda", "Dog", "Panda", "Panda", "Cat", "Cat", "Dog", "Dog", "Panda", "Cat", "Cat", "Dog", "Cow", "Cat", "Cow", "Panda", "Panda", "Dog", "Cow", "Cat", "Dog", "Dog", "Cat", "Panda", "Dog", "Cow", "Cat", "Dog", "Cow", "Panda", "Cat", "Cat", "Cow", "Panda", "Dog", "Cat", "Cow", "Dog", "Dog", "Cow", "Dog", "Cow", "Cat", "Cat", "Cow", "Cow", "Dog", "Cat", "Cow", "Dog", "Panda", "Panda", "Dog", "Cat"}
